#cloud-config
groups:
  - sysadmin: [root, sys]
  - cloud-users

users:
  - name: admin
    gecos: Admin user
    primary_group: admin
    groups: [sysadmin, cloud-users]
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${admin_public_ssh_key}

package_update: true
package_upgrade: true

packages:
  - curl
  - python3
  - iptables
  - nftables
  - openssh-server
