name: default

socket_io:
  url: "http://localhost:8081/socket.io/"
  event_name: "message"
  namespace: "/"

runtime:
  address: "/var/run/containerd.sock"
  snapshotter: "overlayfs"
  data_store_path: "/var/lib/minici"
