name: default

socket_io:
  address: "http://localhost:8080"
  endpoint: "/api/worker/events"
  event_namespace: "events"

runtime:
  address: "/var/run/containerd.sock"
  snapshotter: "overlayfs"
  data_store_path: "/var/lib/minici"
